import {
  Accordion,
  AccordionButton,
  AccordionIcon,
  AccordionItem,
  AccordionPanel,
  Box,
} from '@chakra-ui/react'
import type {NextPage} from 'next'
import Head from 'next/head'
import Image from 'next/image'
import MainHeader from '../components/MainHeader'
import MainLayout from '../components/MainLayout'
import MoreRandomImages from '../components/MoreRandomImages'
import RandomImage from '../components/RandomImage'
import styles from '../styles/Home.module.css'

const Home: NextPage = () => {
  let n = 0
  const handleClick = () => {
    n = 1
  }
  return (
    // <div className={styles.container}>
    <MainLayout>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {/* <header className={styles.site_header}>
        <nav>
          <ul className={styles.nav_list}>
            <li className={styles.list_reset}>
              <a href="#">About</a>
            </li>
            <li className={styles.list_reset}>
              <a href="#">Blog</a>
            </li>
            <li className={styles.list_reset}>
              <a href="#">Register</a>
            </li>
            <li className={styles.list_reset}>
              <a href="#">Login</a>
            </li>
          </ul>
        </nav>
      </header> */}
      {/* <MainHeader /> */}

      <main>
        <div
          className={styles.homepage_hero}
          style={{
            backgroundImage:
              "url('https://images.unsplash.com/photo-1557264337-e8a93017fe92?ixlib=rb-1.2.1&ixid=MnwxMjA3fDB8MHxwaG90by1wYWdlfHx8fGVufDB8fHx8&auto=format&fit=crop&w=1170&q=80')",
          }}
        ></div>
        <section className={styles.homepage_section}>
          <div className={styles.homepage_section_container}>
            <h1>
              Don't miss your
              <br />
              perfect shot
            </h1>
            <p>
              Snapsure tells you when it’s possible to take the shots you want
              to take. There’s nothing worse than missing an opportunity to take
              photo you’ve been thinking about for months, so we pull in data
              from dozens of sources to tell you when the stars—or time, sunset,
              tide, weather, and lots more—align.
            </p>
            <a href="#">
              <button className={styles.homepage_section_signup}>
                Get Started
              </button>
            </a>
          </div>
        </section>
        <div className={styles.lower_section}>
          <RandomImage />
          <MoreRandomImages />
          <RandomImage />
          {/* <Accordion defaultIndex={[0, 1]} allowMultiple>
            <AccordionItem>
              <h2>
                <AccordionButton>
                  <Box flex="1" textAlign="left">
                    Section 1 title
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel pb={4}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </AccordionPanel>
            </AccordionItem>

            <AccordionItem>
              <h2>
                <AccordionButton>
                  <Box flex="1" textAlign="left">
                    Section 2 title
                  </Box>
                  <AccordionIcon />
                </AccordionButton>
              </h2>
              <AccordionPanel pb={4}>
                Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do
                eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut
                enim ad minim veniam, quis nostrud exercitation ullamco laboris
                nisi ut aliquip ex ea commodo consequat.
              </AccordionPanel>
            </AccordionItem>
          </Accordion> */}
        </div>
      </main>
    </MainLayout>
  )
}

export default Home
